#version: '3.8'

services:
    database:
        container_name: "psql_cont"
        image: postgres:15.4-alpine
        env_file:
            - ./db.env
        #volumes:
        #    - ./db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - internal-back

    app:
        container_name: "deploy-app-1"
        build:
            context: ./../
            dockerfile: Dockerfile
        restart: always
#        ports:
#            - "5000:5000"
        networks:
            - front-back
            - internal-back

networks:
    front-back:
        name: front-back
    internal-back:
        name: internal-back