#version: '3.8'

services:
    database:
        container_name: "psql_cont"
        image: postgres:15.4-alpine
        env_file:
            - ./db.env
#        volumes:
#            - ./db-data:/var/lib/postgresql/data
        ports:
            - "5434:5432"
        networks:
            - internal-back

networks:
    front-back:
        name: front-back
    internal-back:
        name: internal-back